# Generated by Django 6.0.6 on 2026-07-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
